
package de.jxws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ServerImplementorService", targetNamespace = "http://jxws.de/", wsdlLocation = "http://10.10.1.54:8080/jaxws/server?WSDL")
public class ServerImplementorService
    extends Service
{

    private final static URL SERVERIMPLEMENTORSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(de.jxws.ServerImplementorService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = de.jxws.ServerImplementorService.class.getResource(".");
            url = new URL(baseUrl, "http://10.10.1.54:8080/jaxws/server?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.10.1.54:8080/jaxws/server?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SERVERIMPLEMENTORSERVICE_WSDL_LOCATION = url;
    }

    public ServerImplementorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServerImplementorService() {
        super(SERVERIMPLEMENTORSERVICE_WSDL_LOCATION, new QName("http://jxws.de/", "ServerImplementorService"));
    }

    /**
     * 
     * @return
     *     returns Server
     */
    @WebEndpoint(name = "ServerImplementorPort")
    public Server getServerImplementorPort() {
        return super.getPort(new QName("http://jxws.de/", "ServerImplementorPort"), Server.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Server
     */
    @WebEndpoint(name = "ServerImplementorPort")
    public Server getServerImplementorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jxws.de/", "ServerImplementorPort"), Server.class, features);
    }

}
